# Generated by Django 5.0.7 on 2024-08-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Water', 'Water'), ('Education', 'Education'), ('Charity', 'Charity'), ('Medical Aid', 'Medical Aid')], default='education', max_length=50),
            preserve_default=False,
        ),
    ]
