# Generated by Django 5.0.7 on 2024-08-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='charity.blog'),
            preserve_default=False,
        ),
    ]
