# Generated by Django 5.0.7 on 2024-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ManyToManyField(to='charity.blog'),
        ),
    ]
