# Generated by Django 5.0.7 on 2024-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0016_cause_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cause',
            name='raised',
            field=models.PositiveIntegerField(),
        ),
    ]
