# Generated by Django 5.0.7 on 2024-08-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_alter_cause_goal_alter_cause_raised'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_cause',
            old_name='blog',
            new_name='cause',
        ),
    ]
