# Generated by Django 5.0.7 on 2024-08-05 12:01

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0018_rename_blog_comment_cause_cause'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Blogs comments'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='event',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='events'),
        ),
    ]
