# Generated by Django 5.0.7 on 2024-08-05 12:03

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0019_alter_comment_options_rename_image_event_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 300], upload_to='blogs'),
        ),
    ]
