# Generated by Django 5.0.7 on 2024-08-05 12:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0020_remove_blog_image_blog_image_1_blog_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/causes/des_nRUEWzA.png', force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='blogs'),
            preserve_default=False,
        ),
    ]
