# Generated by Django 5.0.7 on 2024-08-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0023_payment_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charity.cause'),
        ),
    ]
