# Generated by Django 5.0.7 on 2024-08-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0024_payment_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='raised',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
