# Generated by Django 5.0.7 on 2024-08-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0025_alter_cause_raised'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
